### ISSUE TITLE
Kerguelen (Province ID 3114) cannot be added to a trade company, but every other province in the state can

### ISSUE THREAD

**Issue by phlnx** [ExtendedTimeline/ExtendedTimeline#101]
Not sure if it is desired or not.

Kerguelen can only be colonised later in game as it is a "Hard to colonise" province.

Every other province in its state (Christmas Island (1998), Cocos Island (1644), Hollhavai (1101), Maldives (1248)) can be added to a trade company.

**Comment by AndreasBrostrom** [comment]
Think you made a issue on the wrong mod.

Hearts of iron 4 don't have trade companies 😅

**Comment by phlnx** [comment]
Deeply sorry, I am an idiot. Thank you for being corteous about it.
